apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-signoz
  name: signoz-signoz
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: opamp
    port: 4320
    protocol: TCP
    targetPort: opamp
  selector:
    app.kubernetes.io/component: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz-signoz
  type: ClusterIP
