apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-ingester
  name: signoz-ingester
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: health
    port: 13133
    protocol: TCP
    targetPort: 13133
  selector:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz-ingester
  type: ClusterIP
