apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-ingester
  name: signoz-ingester
