apiVersion: v1
data:
  custom-functions.xml: |
    functions:
      argument:
          - name: buckets
            type: Array(Float64)
          - name: counts
            type: Array(Float64)
          - name: quantile
            type: Array(Float64)
      command: ./histogramQuantile
      format: CSV
      name: histogramQuantile
      return_type: Float64
      type: executable
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: telemetrystore
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-clickhouse
    app.kubernetes.io/part-of: signoz
  name: signoz-clickhouse-custom-functions
