databases:
- databaseName: signoz
  ipAllowList: []
  name: signoz-metastore-postgres
  plan: free
  postgresMajorVersion: "16"
  user: signoz
services:
- disk:
    mountPath: /var/lib/clickhouse-keeper
    name: signoz-telemetrykeeper-clickhousekeeper-0-data
    sizeGB: 5
  dockerContext: configs/telemetrykeeper
  dockerfilePath: configs/telemetrykeeper/Dockerfile
  name: signoz-telemetrykeeper-clickhousekeeper-0
  plan: standard
  runtime: docker
  type: pserv
- disk:
    mountPath: /var/lib/clickhouse
    name: signoz-telemetrystore-clickhouse-0-0-data
    sizeGB: 20
  dockerContext: configs/telemetrystore
  dockerfilePath: configs/telemetrystore/Dockerfile
  envVars:
  - key: CLICKHOUSE_SKIP_USER_SETUP
    value: "1"
  - key: CLICKHOUSE_CONFIG
    value: /etc/clickhouse-server/config.yaml
  - fromService:
      name: signoz-telemetrykeeper-clickhousekeeper-0
      property: host
      type: pserv
    key: DEPENDENCY_LINK_0
  name: signoz-telemetrystore-clickhouse-0-0
  plan: standard
  runtime: docker
  type: pserv
- dockerContext: configs/ingester
  dockerfilePath: configs/ingester/Dockerfile
  envVars:
  - key: SIGNOZ_OTEL_COLLECTOR_TIMEOUT
    value: 10m
  - fromService:
      name: signoz-telemetrystore-clickhouse-0-0
      property: host
      type: pserv
    key: DEPENDENCY_LINK_0
  name: signoz-ingester-0
  plan: standard
  runtime: docker
  type: pserv
- envVars:
  - key: SIGNOZ_SQLSTORE_PROVIDER
    value: postgres
  - key: SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN
    value: tcp://signoz-telemetrystore-clickhouse-0-0:9000
  - key: SIGNOZ_TELEMETRYSTORE_PROVIDER
    value: clickhouse
  - fromDatabase:
      name: signoz-metastore-postgres
      property: connectionString
    key: SIGNOZ_SQLSTORE_POSTGRES_DSN
  - fromService:
      name: signoz-telemetrystore-clickhouse-0-0
      property: host
      type: pserv
    key: DEPENDENCY_LINK_0
  healthCheckPath: /api/v1/health
  image:
    url: signoz/signoz:latest
  name: signoz-signoz-0
  plan: standard
  runtime: image
  type: web
- dockerCommand: |
    /bin/sh -c /signoz-otel-collector migrate bootstrap --clickhouse-dsn=$CLICKHOUSE_DSN
      && /signoz-otel-collector migrate sync up --clickhouse-dsn=$CLICKHOUSE_DSN
      && /signoz-otel-collector migrate async up --clickhouse-dsn=$CLICKHOUSE_DSN
  envVars:
  - key: CLICKHOUSE_DSN
    value: tcp://signoz-telemetrystore-clickhouse-0-0:9000
  - key: SIGNOZ_OTEL_COLLECTOR_TIMEOUT
    value: 10m
  - fromService:
      name: signoz-telemetrystore-clickhouse-0-0
      property: host
      type: pserv
    key: DEPENDENCY_LINK_0
  image:
    url: signoz/signoz-otel-collector:latest
  name: signoz-schema-migrator
  plan: standard
  preDeployCommand: /signoz-otel-collector migrate ready --clickhouse-dsn=${CLICKHOUSE_DSN}
    --timeout 60s
  runtime: image
  type: worker
