apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: signoz
resources:
- namespace.yaml
- clickhouse-operator
- telemetrystore/clickhouse
- telemetrykeeper/clickhousekeeper
- telemetrystore-migrator
- metastore/postgres
- signoz
- ingester
