apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: signoz-telemetrystore-clickhouse-operator
    app.kubernetes.io/name: signoz-telemetrystore-clickhouse-operator
    app.kubernetes.io/version: 0.25.3
  name: signoz-telemetrystore-clickhouse-operator
