apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: signoz-telemetrystore-clickhouse-operator
    app.kubernetes.io/name: signoz-telemetrystore-clickhouse-operator
    app.kubernetes.io/version: 0.25.3
  name: signoz-telemetrystore-clickhouse-operator-metrics
spec:
  ports:
  - name: ch-metrics
    port: 8888
  - name: op-metrics
    port: 9999
  selector:
    app.kubernetes.io/instance: signoz-telemetrystore-clickhouse-operator
    app.kubernetes.io/name: signoz-telemetrystore-clickhouse-operator
