apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metastore
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-metastore
  name: signoz-metastore
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: metastore
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz-metastore
  type: ClusterIP
